### ISSUE TITLE
getting "duplicated key" warning when i start the server

### ISSUE THREAD

**Issue by fredguest** [jtrupiano/rack-rewrite#65]
this is the server log after running "rails s":

=> Booting Puma
=> Rails 4.1.5 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
/Users/username/.rvm/gems/ruby-2.2.0@myapp/gems/rack-rewrite-1.5.0/lib/rack/rewrite/rule.rb:172: warning: duplicated key at line 173 ignored: "Content-Type"
Puma 2.10.2 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:3000

pull request made: https://github.com/jtrupiano/rack-rewrite/pull/66

**Comment by travisjeffery** [comment]
thanks. released in 1.5.1

**Comment by fredguest** [comment]
nice, thanks!
