### ISSUE TITLE
SSL redirect does not save path

### ISSUE THREAD

**Issue by KaoruDev** [jtrupiano/rack-rewrite#74]
I have this in my `config/production.rb` file:

```ruby
  config.middleware.insert_before(Rack::Runtime, Rack::Rewrite) do
    r302 %r{.*}, 'https://www.mydomain.com$&', :scheme => 'http'
  end
```

I expect when i type `http://www.mydomain.com/foo/bar` to be redirected to `https://www.mydomain.com/foo/bar` but instead get redirected to  `https://www.mydomain.com/`

how can I pass the path / query string ( if any ) to ssl endpoints

**Comment by vidmantas** [comment]
I've tried to replicate it https://github.com/jtrupiano/rack-rewrite/pull/75 but without success. Maybe something more is involved here?

**Comment by KaoruDev** [comment]
hrmm yeah we fixed the problem by setting up an nginx redirect ( or something I honestly don't know =P ) I'll go ahead and close this issue, thanks for taking a look!
